name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Temporarily disable credential store
        run: |
          # Backup original config
          cp ~/.docker/config.json ~/.docker/config.json.backup
          
          # Remove credsStore to use direct auth storage
          python3 -c "
          import json
          with open('$HOME/.docker/config.json', 'r') as f:
              config = json.load(f)
          config.pop('credsStore', None)
          with open('$HOME/.docker/config.json', 'w') as f:
              json.dump(config, f, indent=2)
          "

      - name: Login to registry
        run: |
          echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login ${{ secrets.REGISTRY_URL }} -u "${{ secrets.REGISTRY_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.REGISTRY_URL }}/pawtrack:latest .
          docker push ${{ secrets.REGISTRY_URL }}/pawtrack:latest

      - name: Clean up
        run: |
          docker logout ${{ secrets.REGISTRY_URL }} || true
          mv ~/.docker/config.json.backup ~/.docker/config.json
        if: always()